# Generated by Django 5.2 on 2025-09-04 23:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("X (Twitter)", "X (Twitter)"),
                            ("Next Sosyal", "Next Sosyal"),
                            ("Instagram", "Instagram"),
                        ],
                        max_length=40,
                    ),
                ),
                ("mainHashtag", models.CharField(blank=True, null=True)),
                ("sentiment", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "inclination",
                    models.CharField(
                        choices=[
                            ("Çok Olumlu", "Çok Olumlu"),
                            ("Olumlu", "Olumlu"),
                            ("Nötr", "Nötr"),
                            ("Olumsuz", "Olumsuz"),
                            ("Çok Olumsuz", "Çok Olumsuz"),
                        ],
                        default="",
                    ),
                ),
                (
                    "hashtags_list",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                ("topics_list", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("İç Anadolu Bölgesi", "İç Anadolu Bölgesi"),
                            ("Doğu Anadolu Bölgesi", "Doğu Anadolu Bölgesi"),
                            ("Güneydoğu Anadolu Bölgesi", "Güneydoğu Anadolu Bölgesi"),
                            ("Ege Bölgesi", "Ege Bölgesi"),
                            ("Marmara Bölgesi", "Marmara Bölgesi"),
                            ("Akdeniz Bölgesi", "Akdeniz Bölgesi"),
                            ("Karadeniz Bölgesi", "Karadeniz Bölgesi"),
                        ]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NationalDataLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("topics_list", models.JSONField(blank=True, default=dict, null=True)),
                ("posts", models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="DataofPlatforms",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("posts", models.PositiveBigIntegerField()),
                ("mainTopic", models.CharField(blank=True, null=True)),
                ("mainHashtag", models.CharField(blank=True, null=True)),
                ("sentiment", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "inclination",
                    models.CharField(
                        choices=[
                            ("Çok Olumlu", "Çok Olumlu"),
                            ("Olumlu", "Olumlu"),
                            ("Nötr", "Nötr"),
                            ("Olumsuz", "Olumsuz"),
                            ("Çok Olumsuz", "Çok Olumsuz"),
                        ],
                        default="",
                    ),
                ),
                (
                    "hashtags_list",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                ("topics_list", models.JSONField(blank=True, default=dict, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platforms",
                        to="province_data.city",
                    ),
                ),
            ],
        ),
    ]
