# Generated by Django 5.2 on 2025-09-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("province_data", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="dataofplatforms",
            name="name",
            field=models.CharField(
                choices=[
                    ("X (Twitter)", "X (Twitter)"),
                    ("NSosyal", "NSosyal"),
                    ("Instagram", "Instagram"),
                ],
                max_length=40,
            ),
        ),
    ]
